[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
python_version = "3.12"
ignore_missing_imports = false
follow_imports = "silent"
strict_optional = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
allow_untyped_calls = true
